title: "MSWEP"
description: "Global high-resolution precipitation dataset combining gauge, satellite, and reanalysis data. MSWEP supports hydrological and climate research by providing consistent precipitation estimates from 1979 to present."

recipes:
  - id: "MSWEP"
    object: "recipe:MSWEP"

provenance:
  providers:
    - name: "GloH2O"
      description: "GloH2O develops and distributes the MSWEP dataset, blending multiple data sources to provide global precipitation estimates for water resources and climate-related applications."
      roles:
        - data provider
        - research organisation
      url: "https://www.gloh2o.org/"

  license: "Creative Commons Attribution 4.0 (CC BY 4.0)"

acknowledgements: >
  The MSWEP dataset is developed by **GloH2O** and blends rain gauge data, satellite observations, and reanalysis to produce a globally consistent precipitation product. We thank the data providers and acknowledge the efforts of researchers who have validated and improved MSWEP over the years. More details and access are available at the [GloH2O MSWEP page](https://www.gloh2o.org/ppdist/).

citation:
  - authors: "Beck, H.E., Wood, E.F., Pan, M., Fisher, C.K., Miralles, D.G., van Dijk, A.I.J.M., McVicar, T.R., Adler, R.F."
    year: 2019
    title: "MSWEP V2 global 3-hourly 0.1° precipitation: Methodology and quantitative assessment."
    journal: "Bulletin of the American Meteorological Society"
    volume: 100
    pages: 473–500
    doi: "10.1175/BAMS-D-17-0138.1"

contact:
  email: "mswep@gloh2o.org"

maintainers:
  - name: "Mitra Cattry"
    github: "mitraA90"
  - name: "Raphael Hagen"
    github: "norlandrhagen"
